<a href="https://colab.research.google.com/github/khatriprashanna10-pixel/khatriprashanna10-pixel/blob/main/workshop6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Name : Prashanna Khatri

Uni id : 2637881

Part 1: Create and Understand Ndarray:
Ndarray object represents N-dimensional array. Ndarray has different properties/attributes,
which are useful information about the ndarray object.
Problem 1: Create a 2D ndarray of type Integer, e.g., �
1 2 3
4 5 6
7 8 9
� and see its properties.

In [17]:
import numpy as np

A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
print("Shape:", A.shape)
print("Dimensions:", A.ndim)
print("Data Type:", A.dtype)
print("Size:", A.size)
print("Item Size:", A.itemsize)
print("Total Bytes:", A.nbytes)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Shape: (3, 3)
Dimensions: 2
Data Type: int64
Size: 9
Item Size: 8
Total Bytes: 72


Problem 2: Create a 2D ndarray (matrix) of shape (4,5) with all elements equal to 3.0 and print
the matrix.

In [18]:
matrix = np.ones((4,5)) * 3.0
print(matrix)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


Problem 3: What is the other way to create the same matrix as above?

In [19]:
matrix = np.full((4,5), 3.0)
print(matrix)

[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


Problem 4: Construct a matrix �𝑎𝑎𝑖𝑖𝑖𝑖 � of shape (3,3) whose elements are given by 𝑎𝑎𝑖𝑖𝑖𝑖 = 1
2 |𝑖𝑖 − 3𝑗𝑗

In [5]:
A = np.zeros((3,3))
for i in range(3):
    for j in range(3):
        A[i,j] = 0.5 * abs((i+1) - 3*(j+1))
print(A)

[[1.  2.5 4. ]
 [0.5 2.  3.5]
 [0.  1.5 3. ]]


Problem 5: Construct a diagonal matrix of shape (4,4) whose diagonal elements are [1,2,3,4]

In [20]:
D = np.diag([1,2,3,4])
print(D)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


Problem 6: Construct a matrix of shape (4,5) with whatever elements, and then slice it to obtain
a matrix of shape (3,3) that contains only upper-left portion of the original matrix

In [8]:
A = np.array([[1,2,3,4,5],
              [6,7,8,9,10],
              [11,12,13,14,15],
              [16,17,18,19,20]])
print("Original Matrix:")
print(A)
B = A[:3,:3]
print("\nSliced Matrix:")
print(B)

Original Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Sliced Matrix:
[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


Part 2: Operations on Vectors and Matrices

Problem 1: Create two matrices 𝑨𝑨 = �
1 2 3
4 5 6
7 8 9
� and 𝑩𝑩 = �1 1 1
2 2 2�. Add them together. What
do you observe? Give the explanation behind it.

In [11]:
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

B = np.array([[1,1,1],
              [2,2,2]])

The matrices have different shapes:

A → (3,3)

B → (2,3)

Matrices must have exactly the same dimensions to be added. Therefore NumPy raises a ValueError.

Problem 2: Given a matrix and a vector, write a Python function that performs Matrix-Vector
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [16]:
import numpy as np

matrix = np.array([[3,3,3],
                   [3,3,3],
                   [3,3,3]])

vector = np.array([[2],
                   [2],
                   [2]])

print("Matrix =")
print(matrix)

print("Vector =")
print(vector)

# Method 1
result1 = np.matmul(matrix, vector)

print("Result1 =")
print(result1)

# Method 2
result2 = np.dot(matrix, vector)

print("Result2 =")
print(result2)

Matrix =
[[3 3 3]
 [3 3 3]
 [3 3 3]]
Vector =
[[2]
 [2]
 [2]]
Result1 =
[[18]
 [18]
 [18]]
Result2 =
[[18]
 [18]
 [18]]


Problem 3: Given two compatible matrices, write a Python function that performs Matrix-Matrix
product. Check your result with NumPy built-in function to perform Matrix-Vector/Matrix-
Matrix product.

In [14]:
def matrix_matrix_product(A, B):

    rows = len(A)
    cols = len(B[0])
    common = len(B)

    result = []

    for i in range(rows):
        row = []
        for j in range(cols):
            total = 0
            for k in range(common):
                total += A[i][k] * B[k][j]
            row.append(total)
        result.append(row)

    return result

A = [[1,2],
     [3,4]]

B = [[5,6],
     [7,8]]

print("Manual:")
print(matrix_matrix_product(A,B))

A_np = np.array(A)
B_np = np.array(B)

print("\nNumPy:")
print(np.dot(A_np,B_np))

Manual:
[[19, 22], [43, 50]]

NumPy:
[[19 22]
 [43 50]]


Problem 4: Given a matrix, write a Python function that checks if it is a symmetric matrix

In [15]:
def is_symmetric(matrix):
    matrix = np.array(matrix)
    return np.array_equal(matrix, matrix.T)

A = np.array([[1,2,3],
              [2,5,6],
              [3,6,9]])

B = np.array([[1,2],
              [3,4]])

print("A is symmetric:", is_symmetric(A))
print("B is symmetric:", is_symmetric(B))

A is symmetric: True
B is symmetric: False
